import { useState } from "react";
import { generateReportPDF } from "@/utils/generateReportPDF";
import {
  Download,
  Loader2,
  AlertTriangle,
  CheckCircle,
  XCircle,
  Clock,
  Shield,
  Lightbulb,
  Users,
  TrendingUp,
  CalendarDays,
} from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import type { ProjectReport, Severity } from "@/types/report.types";

interface ReportDetailModalProps {
  report: ProjectReport | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
  orgName?: string;
}

function healthBadgeClass(status: string) {
  if (status === "Critical") return "bg-red-100 text-red-700 border-red-200";
  if (status === "At Risk") return "bg-orange-100 text-orange-700 border-orange-200";
  return "bg-green-100 text-green-700 border-green-200";
}

function healthIcon(status: string) {
  if (status === "Critical") return <XCircle size={12} />;
  if (status === "At Risk") return <AlertTriangle size={12} />;
  return <CheckCircle size={12} />;
}

function timelineBadgeClass(status: string) {
  if (status === "Delayed") return "bg-red-100 text-red-700 border-red-200";
  if (status === "Ahead of Schedule") return "bg-blue-100 text-blue-700 border-blue-200";
  return "bg-green-100 text-green-700 border-green-200";
}

function severityBadgeClass(severity: Severity) {
  if (severity === "high") return "bg-red-100 text-red-700 border-red-200";
  if (severity === "medium") return "bg-yellow-100 text-yellow-700 border-yellow-200";
  return "bg-gray-100 text-gray-600 border-gray-200";
}

function healthScoreColor(score: number) {
  if (score >= 70) return "text-green-700 border-green-300 bg-green-50";
  if (score >= 40) return "text-orange-700 border-orange-300 bg-orange-50";
  return "text-red-700 border-red-300 bg-red-50";
}

export default function ReportDetailModal({
  report,
  open,
  onOpenChange,
  orgName,
}: ReportDetailModalProps) {
  const [exporting, setExporting] = useState(false);

  if (!report) return null;

  const projectTitle =
    typeof report.projectId === "object" ? report.projectId.title : "Project";
  const generatedBy =
    typeof report.generatedBy === "object" ? report.generatedBy.name : "—";
  const generatedDate = new Date(report.createdAt).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const handleDownloadPDF = () => {
    setExporting(true);
    try {
      generateReportPDF(report, orgName);
    } finally {
      setExporting(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
        <DialogContent
          className="!max-w-[1400px] !w-[95vw] max-h-[90vh] overflow-y-auto overflow-x-hidden p-0"
          showCloseButton={true}
        >
          {/* Modal Header - Landscape Layout */}
          <DialogHeader className="px-4 sm:px-8 pt-6 pb-4 border-b bg-muted/30">
            <div className="flex items-center justify-between gap-4 sm:gap-6">
              <div className="flex-1 min-w-0">
                <DialogTitle className="text-xl font-bold text-foreground mb-2">
                  {projectTitle}
                </DialogTitle>
                <div className="flex items-center gap-4 text-sm text-muted-foreground">
                  <span className="flex items-center gap-1.5">
                    <Users size={14} /> Generated by {generatedBy}
                  </span>
                  <span className="flex items-center gap-1.5">
                    <CalendarDays size={14} /> {generatedDate}
                  </span>
                </div>
              </div>

              {/* Health Score & Status Badges */}
              <div className="flex items-center gap-4">
                <div className="flex gap-2">
                  <span
                    className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-sm font-medium border ${healthBadgeClass(report.healthStatus)}`}
                  >
                    {healthIcon(report.healthStatus)}
                    {report.healthStatus}
                  </span>
                  <span
                    className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-sm font-medium border ${timelineBadgeClass(report.timeline)}`}
                  >
                    <Clock size={14} />
                    {report.timeline}
                  </span>
                </div>
                <div
                  className={`flex flex-col items-center justify-center w-20 h-20 rounded-full border-3 shrink-0 ${healthScoreColor(report.healthScore)}`}
                >
                  <span className="text-2xl font-bold leading-none">{report.healthScore}</span>
                  <span className="text-xs leading-none mt-1 opacity-70">/ 100</span>
                </div>
              </div>
            </div>
          </DialogHeader>

          {/* Modal Body - Landscape Grid Layout */}
          <div className="px-4 sm:px-8 py-6">
            {/* Metrics Row */}
            <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4 mb-6">
              {[
                {
                  label: "Total Tasks",
                  value: report.projectSnapshot.totalTasks,
                  icon: <TrendingUp size={16} />,
                },
                {
                  label: "Completion",
                  value: `${report.projectSnapshot.completionPercentage}%`,
                  icon: <CheckCircle size={16} />,
                },
                {
                  label: "Overdue",
                  value: report.projectSnapshot.overdueCount,
                  icon: <AlertTriangle size={16} />,
                  alert: report.projectSnapshot.overdueCount > 0,
                },
                {
                  label: "Hours Logged",
                  value: `${report.projectSnapshot.totalLoggedHours}h`,
                  sub: `/ ${report.projectSnapshot.totalEstimatedHours}h est.`,
                  icon: <Clock size={16} />,
                },
              ].map((m, i) => (
                <div key={i} className="rounded-xl bg-muted/50 border border-border px-4 py-4 hover:bg-muted/70 transition-colors">
                  <div className="flex items-center gap-2 mb-2 text-muted-foreground">
                    {m.icon}
                    <span className="text-xs font-medium uppercase tracking-wide">{m.label}</span>
                  </div>
                  <div
                    className={`text-3xl font-bold ${m.alert ? "text-destructive" : "text-foreground"}`}
                  >
                    {m.value}
                  </div>
                  {"sub" in m && m.sub && (
                    <div className="text-xs text-muted-foreground mt-1">{m.sub}</div>
                  )}
                </div>
              ))}
            </div>

            {/* Two Column Layout */}
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 sm:gap-6">
              {/* Left Column */}
              <div className="space-y-6">
                {/* Executive Summary */}
                <Section icon={<TrendingUp size={14} />} title="Executive Summary">
                  <div className="rounded-lg bg-muted/30 border border-border p-4">
                    <p className="text-sm text-foreground leading-relaxed">
                      {report.executiveSummary}
                    </p>
                  </div>
                </Section>

                {/* Key Findings */}
                {report.keyFindings.length > 0 && (
                  <Section icon={<Lightbulb size={14} />} title="Key Findings">
                    <div className="rounded-lg bg-muted/30 border border-border p-4">
                      <ul className="space-y-3">
                        {report.keyFindings.map((f, i) => (
                          <li key={i} className="flex gap-3 text-sm text-foreground">
                            <span className="flex items-center justify-center w-6 h-6 rounded-full bg-primary text-primary-foreground font-bold text-xs shrink-0">
                              {i + 1}
                            </span>
                            <span className="pt-0.5">{f}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  </Section>
                )}

                {/* Team Performance */}
                {report.teamPerformance && (
                  <Section icon={<Users size={14} />} title="Team Performance">
                    <div className="rounded-lg bg-muted/30 border border-border p-4">
                      <p className="text-sm text-foreground leading-relaxed">
                        {report.teamPerformance}
                      </p>
                    </div>
                  </Section>
                )}
              </div>

              {/* Right Column */}
              <div className="space-y-6">
                {/* Risks */}
                {report.risks.length > 0 && (
                  <Section icon={<Shield size={14} />} title="Risk Register">
                    <div className="space-y-3">
                      {report.risks.map((risk, i) => (
                        <div
                          key={i}
                          className="rounded-lg border-2 border-border bg-background p-4 hover:shadow-md transition-shadow"
                        >
                          <div className="flex items-center gap-2 mb-2">
                            <span
                              className={`inline-flex items-center px-2.5 py-1 rounded-full text-xs font-semibold border capitalize ${severityBadgeClass(risk.severity)}`}
                            >
                              {risk.severity}
                            </span>
                            <span className="text-sm font-semibold text-foreground">
                              {risk.title}
                            </span>
                          </div>
                          <p className="text-sm text-muted-foreground leading-relaxed">{risk.description}</p>
                        </div>
                      ))}
                    </div>
                  </Section>
                )}

                {/* Recommendations */}
                {report.recommendations.length > 0 && (
                  <Section icon={<Lightbulb size={14} />} title="Recommendations">
                    <div className="space-y-3">
                      {report.recommendations.map((rec, i) => (
                        <div
                          key={i}
                          className="rounded-lg border-2 border-border bg-background p-4 hover:shadow-md transition-shadow"
                        >
                          <div className="flex items-center gap-2 mb-2">
                            <span
                              className={`inline-flex items-center px-2.5 py-1 rounded-full text-xs font-semibold border capitalize ${severityBadgeClass(rec.priority)}`}
                            >
                              {rec.priority}
                            </span>
                            <span className="text-sm font-semibold text-foreground">
                              {rec.title}
                            </span>
                          </div>
                          <p className="text-sm text-muted-foreground leading-relaxed">{rec.action}</p>
                        </div>
                      ))}
                    </div>
                  </Section>
                )}
              </div>
            </div>
          </div>

          {/* Footer */}
          {/* <DialogFooter className="px-4 sm:px-8 py-4 border-t bg-muted/30">
            <Button variant="outline" onClick={() => onOpenChange(false)}>
              Close
            </Button>
            <Button onClick={handleDownloadPDF} disabled={exporting}>
              {exporting ? (
                <Loader2 size={16} className="animate-spin mr-2" />
              ) : (
                <Download size={16} className="mr-2" />
              )}
              {exporting ? "Exporting…" : "Download PDF"}
            </Button>
          </DialogFooter> */}
        </DialogContent>
      </Dialog>
  );
}

function Section({
  icon,
  title,
  children,
}: {
  icon: React.ReactNode;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div>
      <div className="flex items-center gap-2 mb-3">
        <span className="text-primary">{icon}</span>
        <h4 className="text-xs font-bold uppercase tracking-wider text-foreground">
          {title}
        </h4>
      </div>
      {children}
    </div>
  );
}
