import { forwardRef } from "react";
import type { ProjectReport } from "@/types/report.types";

interface ReportPDFProps {
  report: ProjectReport;
  orgName?: string;
}

const severityColor = (s: string) => {
  if (s === "high" || s === "critical") return "#dc2626";
  if (s === "medium") return "#d97706";
  return "#16a34a";
};

const healthColor = (status: string) => {
  if (status === "Critical") return "#dc2626";
  if (status === "At Risk") return "#d97706";
  return "#16a34a";
};

const ReportPDF = forwardRef<HTMLDivElement, ReportPDFProps>(
  ({ report, orgName = "Opervox" }, ref) => {
    const generatedDate = new Date(report.createdAt).toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });
    const generatedBy =
      typeof report.generatedBy === "object" ? report.generatedBy.name : "—";
    const projectTitle =
      typeof report.projectId === "object" ? report.projectId.title : "—";

    return (
      <div
        ref={ref}
        style={{
          width: "794px",
          backgroundColor: "#ffffff",
          fontFamily: "'Segoe UI', Arial, sans-serif",
          fontSize: "13px",
          color: "#1e293b",
          lineHeight: "1.6",
        }}
      >
        {/* Cover Header */}
        <div
          style={{
            background: "#4f46e5",
            padding: "40px 48px 32px",
            color: "#ffffff",
          }}
        >
          <div style={{ fontSize: "11px", letterSpacing: "2px", opacity: 0.8, marginBottom: "8px", textTransform: "uppercase" }}>
            {orgName}
          </div>
          <div style={{ fontSize: "22px", fontWeight: 700, marginBottom: "6px" }}>
            Project Performance Report
          </div>
        
          <div style={{ marginTop: "20px", fontSize: "11px", opacity: 0.75 }}>
            Report Generated: {generatedDate}
          </div>
        </div>

        {/* Metadata Bar */}
        <div
          style={{
            display: "flex",
            gap: "0",
            borderBottom: "1px solid #e2e8f0",
          }}
        >
          {[
            { label: "Health Status", value: report.healthStatus, color: healthColor(report.healthStatus) },
            { label: "Health Score", value: `${report.healthScore} / 100`, color: "#4f46e5" },
            { label: "Timeline", value: report.timeline, color: report.timeline === "On Track" ? "#16a34a" : report.timeline === "Ahead of Schedule" ? "#4f46e5" : "#d97706" },
            { label: "Generated By", value: generatedBy, color: "#475569" },
          ].map((item, i) => (
            <div
              key={i}
              style={{
                flex: 1,
                padding: "16px 20px",
                borderRight: i < 3 ? "1px solid #e2e8f0" : "none",
                backgroundColor: "#f8fafc",
              }}
            >
              <div style={{ fontSize: "10px", color: "#94a3b8", textTransform: "uppercase", letterSpacing: "0.5px", marginBottom: "4px" }}>
                {item.label}
              </div>
              <div style={{ fontWeight: 600, color: item.color, fontSize: "13px" }}>
                {item.value}
              </div>
            </div>
          ))}
        </div>

        <div style={{ padding: "32px 48px" }}>
          {/* Executive Summary */}
          <Section title="Executive Summary">
            <div
              style={{
                backgroundColor: "#f8fafc",
                border: "1px solid #e2e8f0",
                borderRadius: "8px",
                padding: "16px 18px",
                color: "#334155",
                lineHeight: "1.7",
              }}
            >
              {report.executiveSummary}
            </div>
          </Section>

          {/* Key Metrics */}
          <Section title="Key Metrics">
            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr 1fr", gap: "12px" }}>
              {[
                { label: "Total Tasks", value: report.projectSnapshot.totalTasks },
                { label: "Completion", value: `${report.projectSnapshot.completionPercentage}%` },
                { label: "Overdue Tasks", value: report.projectSnapshot.overdueCount, alert: report.projectSnapshot.overdueCount > 0 },
                {
                  label: "Hours Logged",
                  value: `${report.projectSnapshot.totalLoggedHours}h / ${report.projectSnapshot.totalEstimatedHours}h`,
                },
              ].map((m, i) => (
                <div
                  key={i}
                  style={{
                    padding: "14px 16px",
                    borderRadius: "8px",
                    border: "1px solid #e2e8f0",
                    backgroundColor: "#f8fafc",
                    textAlign: "center",
                  }}
                >
                  <div style={{ fontSize: "20px", fontWeight: 700, color: m.alert ? "#dc2626" : "#4f46e5" }}>
                    {m.value}
                  </div>
                  <div style={{ fontSize: "11px", color: "#64748b", marginTop: "4px" }}>{m.label}</div>
                </div>
              ))}
            </div>
          </Section>

          {/* Key Findings — custom div layout (html2canvas doesn't render ol/li reliably) */}
          {report.keyFindings.length > 0 && (
            <Section title="Key Findings">
              <div style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
                {report.keyFindings.map((f, i) => (
                  <div
                    key={i}
                    style={{
                      display: "flex",
                      alignItems: "flex-start",
                      gap: "12px",
                    }}
                  >
                    {/* Number circle */}
                    <div
                      style={{
                        flexShrink: 0,
                        width: "22px",
                        height: "22px",
                        borderRadius: "50%",
                        backgroundColor: "#4f46e5",
                        color: "#ffffff",
                        fontSize: "11px",
                        fontWeight: 700,
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "center",
                        marginTop: "1px",
                      }}
                    >
                      {i + 1}
                    </div>
                    {/* Finding text */}
                    <div style={{ flex: 1, color: "#334155", lineHeight: "1.6", paddingTop: "2px" }}>
                      {f}
                    </div>
                  </div>
                ))}
              </div>
            </Section>
          )}

          {/* Risk Register */}
          {report.risks.length > 0 && (
            <Section title="Risk Register">
              <table style={{ width: "100%", borderCollapse: "collapse", tableLayout: "fixed" }}>
                <colgroup>
                  <col style={{ width: "30%" }} />
                  <col style={{ width: "14%" }} />
                  <col style={{ width: "56%" }} />
                </colgroup>
                <thead>
                  <tr style={{ backgroundColor: "#f1f5f9" }}>
                    {["Risk", "Severity", "Description"].map((h) => (
                      <th
                        key={h}
                        style={{
                          padding: "9px 12px",
                          textAlign: "left",
                          fontSize: "11px",
                          fontWeight: 700,
                          color: "#475569",
                          textTransform: "uppercase",
                          letterSpacing: "0.5px",
                          borderBottom: "2px solid #e2e8f0",
                        }}
                      >
                        {h}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {report.risks.map((risk, i) => (
                    <tr
                      key={i}
                      style={{
                        backgroundColor: i % 2 === 0 ? "#ffffff" : "#f8fafc",
                        borderBottom: "1px solid #e2e8f0",
                      }}
                    >
                      <td style={{ padding: "11px 12px", fontWeight: 600, color: "#1e293b", verticalAlign: "top", wordBreak: "break-word" }}>
                        {risk.title}
                      </td>
                      <td style={{ padding: "11px 12px", verticalAlign: "top" }}>
                        <span
                          style={{
                            display: "inline-block",
                            padding: "3px 10px",
                            borderRadius: "20px",
                            backgroundColor: `${severityColor(risk.severity)}18`,
                            color: severityColor(risk.severity),
                            fontSize: "11px",
                            fontWeight: 700,
                            textTransform: "capitalize",
                            whiteSpace: "nowrap",
                          }}
                        >
                          {risk.severity}
                        </span>
                      </td>
                      <td style={{ padding: "11px 12px", color: "#475569", verticalAlign: "top", lineHeight: "1.6" }}>
                        {risk.description}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </Section>
          )}

          {/* Recommendations */}
          {report.recommendations.length > 0 && (
            <Section title="Recommendations">
              <table style={{ width: "100%", borderCollapse: "collapse", tableLayout: "fixed" }}>
                <colgroup>
                  {/* Give Recommendation column enough room so titles don't wrap to next line */}
                  <col style={{ width: "32%" }} />
                  <col style={{ width: "14%" }} />
                  <col style={{ width: "54%" }} />
                </colgroup>
                <thead>
                  <tr style={{ backgroundColor: "#f1f5f9" }}>
                    {["Recommendation", "Priority", "Action"].map((h) => (
                      <th
                        key={h}
                        style={{
                          padding: "9px 12px",
                          textAlign: "left",
                          fontSize: "11px",
                          fontWeight: 700,
                          color: "#475569",
                          textTransform: "uppercase",
                          letterSpacing: "0.5px",
                          borderBottom: "2px solid #e2e8f0",
                        }}
                      >
                        {h}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {report.recommendations.map((rec, i) => (
                    <tr
                      key={i}
                      style={{
                        backgroundColor: i % 2 === 0 ? "#ffffff" : "#f8fafc",
                        borderBottom: "1px solid #e2e8f0",
                      }}
                    >
                      <td style={{ padding: "11px 12px", fontWeight: 600, color: "#1e293b", verticalAlign: "top", wordBreak: "break-word", lineHeight: "1.5" }}>
                        {rec.title}
                      </td>
                      <td style={{ padding: "11px 12px", verticalAlign: "top" }}>
                        <span
                          style={{
                            display: "inline-block",
                            padding: "3px 10px",
                            borderRadius: "20px",
                            backgroundColor: `${severityColor(rec.priority)}18`,
                            color: severityColor(rec.priority),
                            fontSize: "11px",
                            fontWeight: 700,
                            textTransform: "capitalize",
                            whiteSpace: "nowrap",
                          }}
                        >
                          {rec.priority}
                        </span>
                      </td>
                      <td style={{ padding: "11px 12px", color: "#475569", verticalAlign: "top", lineHeight: "1.6" }}>
                        {rec.action}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </Section>
          )}

          {/* Team Performance */}
          {report.teamPerformance && (
            <Section title="Team Performance">
              <div
                style={{
                  backgroundColor: "#f8fafc",
                  border: "1px solid #e2e8f0",
                  borderRadius: "8px",
                  padding: "16px 18px",
                  color: "#334155",
                  lineHeight: "1.7",
                }}
              >
                {report.teamPerformance}
              </div>
            </Section>
          )}
        </div>

        {/* Footer */}
        <div
          style={{
            borderTop: "1px solid #e2e8f0",
            padding: "14px 48px",
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            backgroundColor: "#f8fafc",
            fontSize: "10px",
            color: "#94a3b8",
          }}
        >
          <span>
            Generated by {generatedBy} on {generatedDate}
          </span>
          <span>{orgName} Project Management</span>
          <span style={{ fontWeight: 600, color: "#64748b", letterSpacing: "1px" }}>
            CONFIDENTIAL
          </span>
        </div>
      </div>
    );
  }
);

ReportPDF.displayName = "ReportPDF";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: "32px" }}>
      {/* Section title with left accent bar */}
      <div style={{ display: "flex", alignItems: "center", gap: "10px", marginBottom: "14px" }}>
        <div
          style={{
            width: "4px",
            height: "18px",
            borderRadius: "2px",
            backgroundColor: "#4f46e5",
            flexShrink: 0,
          }}
        />
        <div
          style={{
            fontSize: "12px",
            fontWeight: 700,
            color: "#1e293b",
            textTransform: "uppercase",
            letterSpacing: "1px",
          }}
        >
          {title}
        </div>
        {/* Thin line filling remaining space */}
        <div style={{ flex: 1, height: "1px", backgroundColor: "#e2e8f0" }} />
      </div>
      {children}
    </div>
  );
}

export default ReportPDF;
