import jsPDF from "jspdf";
import type { ProjectReport } from "@/types/report.types";

// ─── Page constants (mm) ────────────────────────────────────────────────────
const PW = 210;          // page width
const PH = 297;          // page height
const ML = 15;           // left margin
const MR = 15;           // right margin
const CW = PW - ML - MR; // content width = 180
const FOOTER_Y = PH - 12;

// ─── Colour palette ─────────────────────────────────────────────────────────
const C = {
  indigo:      [79,  70,  229] as [number,number,number],
  indigoDark:  [55,  48,  163] as [number,number,number],
  slate800:    [30,  41,   59] as [number,number,number],
  slate700:    [51,  65,   85] as [number,number,number],
  slate500:    [100, 116, 139] as [number,number,number],
  slate400:    [148, 163, 184] as [number,number,number],
  slate200:    [226, 232, 240] as [number,number,number],
  slate100:    [241, 245, 249] as [number,number,number],
  slate50:     [248, 250, 252] as [number,number,number],
  white:       [255, 255, 255] as [number,number,number],
  // severity
  red700:      [185,  28,  28] as [number,number,number],
  red50:       [254, 242, 242] as [number,number,number],
  amber700:    [180,  83,   9] as [number,number,number],
  amber50:     [255, 251, 235] as [number,number,number],
  green700:    [21,  128,  61] as [number,number,number],
  green50:     [240, 253, 244] as [number,number,number],
};

function severityPair(s: string): { bg: [number,number,number]; fg: [number,number,number] } {
  if (s === "high")   return { bg: C.red50,   fg: C.red700 };
  if (s === "medium") return { bg: C.amber50, fg: C.amber700 };
  return                     { bg: C.green50, fg: C.green700 };
}

function healthFg(status: string): [number,number,number] {
  if (status === "Critical")   return C.red700;
  if (status === "At Risk")    return C.amber700;
  return C.green700;
}

function timelineFg(tl: string): [number,number,number] {
  if (tl === "Delayed")           return C.red700;
  if (tl === "Ahead of Schedule") return C.indigo;
  return C.green700;
}

// ─── jsPDF sugar ────────────────────────────────────────────────────────────
function fill(doc: jsPDF, rgb: [number,number,number]) {
  doc.setFillColor(rgb[0], rgb[1], rgb[2]);
}
function stroke(doc: jsPDF, rgb: [number,number,number]) {
  doc.setDrawColor(rgb[0], rgb[1], rgb[2]);
}
function color(doc: jsPDF, rgb: [number,number,number]) {
  doc.setTextColor(rgb[0], rgb[1], rgb[2]);
}

// ─── Main export ─────────────────────────────────────────────────────────────
export function generateReportPDF(report: ProjectReport, orgName = "Opervox"): void {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  const projectTitle = typeof report.projectId === "object" ? report.projectId.title : "Project";
  const generatedBy  = typeof report.generatedBy === "object" ? report.generatedBy.name : "—";
  const generatedDate = new Date(report.createdAt).toLocaleDateString("en-US", {
    year: "numeric", month: "long", day: "numeric",
  });

  // Current Y cursor (mutated by helpers via closure)
  let y = 0;

  // ── Footer (drawn on every page) ──────────────────────────────────────────
  function drawFooter() {
    fill(doc, C.slate100);
    doc.rect(0, FOOTER_Y, PW, 12, "F");
    stroke(doc, C.slate200);
    doc.setLineWidth(0.3);
    doc.line(0, FOOTER_Y, PW, FOOTER_Y);

    doc.setFontSize(7.5);
    doc.setFont("helvetica", "normal");
    color(doc, C.slate400);
    doc.text(`Generated by ${generatedBy} on ${generatedDate}`, ML, FOOTER_Y + 5);
    doc.text(`${orgName} Project Management`, PW / 2, FOOTER_Y + 5, { align: "center" });
    doc.setFont("helvetica", "bold");
    color(doc, C.slate500);
    doc.text("CONFIDENTIAL", PW - MR, FOOTER_Y + 5, { align: "right" });
  }

  // ── Page-break guard ──────────────────────────────────────────────────────
  function need(h: number) {
    if (y + h > FOOTER_Y - 6) {
      drawFooter();
      doc.addPage();
      y = 18;
    }
  }

  // ── Section heading with left accent bar + rule ───────────────────────────
  function sectionTitle(title: string) {
    need(14);
    fill(doc, C.indigo);
    doc.rect(ML, y, 3, 9, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    color(doc, C.slate800);
    doc.text(title.toUpperCase(), ML + 6, y + 6.5);
    const tw = doc.getTextWidth(title.toUpperCase()) + ML + 8;
    stroke(doc, C.slate200);
    doc.setLineWidth(0.3);
    doc.line(tw, y + 3, PW - MR, y + 3);
    y += 12;
  }

  // ── Boxed text block (Executive Summary / Team Performance) ──────────────
  function textBox(text: string) {
    const lines = doc.splitTextToSize(text, CW - 10) as string[];
    const bh = lines.length * 5.2 + 10;
    need(bh + 4);
    fill(doc, C.slate50);
    stroke(doc, C.slate200);
    doc.setLineWidth(0.3);
    doc.rect(ML, y, CW, bh, "FD");
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    color(doc, C.slate700);
    doc.text(lines, ML + 5, y + 8);
    y += bh + 8;
  }

  // ── Generic table (risks / recommendations) ────────────────────────────────
  function drawTable(
    headers: string[],
    colWidths: number[],   // fractions of CW
    rows: { cells: string[]; badge?: { colIndex: number; label: string; severity: string } }[]
  ) {
    const ws = colWidths.map(f => CW * f);
    const headerH = 9;

    // Don't need extra space check here since caller handles it
    fill(doc, C.slate100);
    stroke(doc, C.slate200);
    doc.setLineWidth(0.3);
    doc.rect(ML, y, CW, headerH, "FD");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    color(doc, C.slate500);
    let hx = ML;
    headers.forEach((h, i) => {
      doc.text(h.toUpperCase(), hx + 3, y + 6.3);
      hx += ws[i];
    });
    y += headerH;

    rows.forEach((row, ri) => {
      // Pre-compute line counts per cell to get row height
      let maxLines = 1;
      const cellLines: string[][] = row.cells.map((cell, ci) => {
        if (row.badge?.colIndex === ci) return [""]; // badge cell — single row
        const lines = doc.splitTextToSize(cell, ws[ci] - 6) as string[];
        maxLines = Math.max(maxLines, lines.length);
        return lines;
      });

      const rowH = maxLines * 5.2 + 8;
      need(rowH);

      if (ri % 2 !== 0) {
        fill(doc, C.slate50);
        doc.rect(ML, y, CW, rowH, "F");
      }

      let cx = ML;
      row.cells.forEach((cell, ci) => {
        if (ci === row.badge?.colIndex) {
          // Draw pill badge
          const { bg, fg } = severityPair(row.badge.severity);
          const label = row.badge.label.charAt(0).toUpperCase() + row.badge.label.slice(1);
          doc.setFont("helvetica", "bold");
          doc.setFontSize(8.5);
          const lw = doc.getTextWidth(label);
          const pw2 = lw + 10;
          const ph2 = 7;
          fill(doc, bg);
          stroke(doc, bg);
          doc.roundedRect(cx + 3, y + (rowH - ph2) / 2, pw2, ph2, 3, 3, "FD");
          color(doc, fg);
          doc.text(label, cx + 3 + pw2 / 2, y + (rowH - ph2) / 2 + 5.2, { align: "center" });
        } else {
          doc.setFont(ci === 0 ? "helvetica" : "helvetica", ci === 0 ? "bold" : "normal");
          doc.setFontSize(9.5);
          color(doc, ci === 0 ? C.slate800 : C.slate700);
          doc.text(cellLines[ci], cx + 3, y + 6);
        }
        cx += ws[ci];
      });

      // Row bottom divider
      stroke(doc, C.slate200);
      doc.setLineWidth(0.2);
      doc.line(ML, y + rowH, ML + CW, y + rowH);
      y += rowH;
    });
    y += 8;
  }

  // ════════════════════════════════════════════════════════════════════════════
  // HEADER BANNER
  // ════════════════════════════════════════════════════════════════════════════
  fill(doc, C.indigo);
  doc.rect(0, 0, PW, 52, "F");

  // Org name
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.5);
  color(doc, [200, 200, 255]);
  doc.text(orgName.toUpperCase(), ML, 11);

  // Report title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(17);
  color(doc, C.white);
  doc.text("Project Performance Report", ML, 24);

  // Project title
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11.5);
  color(doc, [210, 210, 255]);
  const ptLines = doc.splitTextToSize(projectTitle, CW) as string[];
  doc.text(ptLines[0], ML, 34);

  // Date
  doc.setFontSize(8.5);
  color(doc, [180, 180, 230]);
  doc.text(`Report Generated: ${generatedDate}`, ML, 45);

  y = 52;

  // ════════════════════════════════════════════════════════════════════════════
  // METADATA BAR
  // ════════════════════════════════════════════════════════════════════════════
  const metaH = 22;
  fill(doc, C.slate50);
  doc.rect(0, y, PW, metaH, "F");
  stroke(doc, C.slate200);
  doc.setLineWidth(0.3);
  doc.line(0, y + metaH, PW, y + metaH);

  const metaCols = [
    { label: "HEALTH STATUS", value: report.healthStatus, fg: healthFg(report.healthStatus) },
    { label: "HEALTH SCORE",  value: `${report.healthScore} / 100`,  fg: C.indigo },
    { label: "TIMELINE",      value: report.timeline,    fg: timelineFg(report.timeline) },
    { label: "GENERATED BY",  value: generatedBy,        fg: C.slate700 },
  ];

  const colW = PW / 4;
  metaCols.forEach((col, i) => {
    const x = i * colW + 5;
    if (i > 0) {
      stroke(doc, C.slate200);
      doc.line(i * colW, y + 4, i * colW, y + metaH - 4);
    }
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    color(doc, C.slate400);
    doc.text(col.label, x, y + 8);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    color(doc, col.fg);
    doc.text(col.value, x, y + 17);
  });

  y += metaH + 8;

  // ════════════════════════════════════════════════════════════════════════════
  // EXECUTIVE SUMMARY
  // ════════════════════════════════════════════════════════════════════════════
  sectionTitle("Executive Summary");
  textBox(report.executiveSummary);

  // ════════════════════════════════════════════════════════════════════════════
  // KEY METRICS
  // ════════════════════════════════════════════════════════════════════════════
  sectionTitle("Key Metrics");
  const metrics = [
    { label: "Total Tasks",   value: String(report.projectSnapshot.totalTasks),                                                    alert: false },
    { label: "Completion",    value: `${report.projectSnapshot.completionPercentage}%`,                                            alert: false },
    { label: "Overdue Tasks", value: String(report.projectSnapshot.overdueCount),                                                  alert: report.projectSnapshot.overdueCount > 0 },
    { label: "Hours Logged",  value: `${report.projectSnapshot.totalLoggedHours}h / ${report.projectSnapshot.totalEstimatedHours}h`, alert: false },
  ];

  const mw = CW / 4 - 2;
  const mh = 22;
  need(mh + 8);

  metrics.forEach((m, i) => {
    const mx = ML + i * (mw + 2.67);
    fill(doc, C.slate50);
    stroke(doc, C.slate200);
    doc.setLineWidth(0.3);
    doc.rect(mx, y, mw, mh, "FD");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    color(doc, m.alert ? C.red700 : C.indigo);
    doc.text(m.value, mx + mw / 2, y + 12, { align: "center" });

    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    color(doc, C.slate400);
    doc.text(m.label, mx + mw / 2, y + 19, { align: "center" });
  });
  y += mh + 10;

  // ════════════════════════════════════════════════════════════════════════════
  // KEY FINDINGS
  // ════════════════════════════════════════════════════════════════════════════
  if (report.keyFindings.length > 0) {
    sectionTitle("Key Findings");
    report.keyFindings.forEach((finding, i) => {
      const lines = doc.splitTextToSize(finding, CW - 18) as string[];
      const rh = lines.length * 5.2 + 6;
      need(rh + 2);

      // Indigo circle with number
      fill(doc, C.indigo);
      doc.circle(ML + 4.5, y + 4.5, 4, "F");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8);
      color(doc, C.white);
      doc.text(String(i + 1), ML + 4.5, y + 6.3, { align: "center" });

      // Finding text — vertically centred beside the circle
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9.5);
      color(doc, C.slate700);
      doc.text(lines, ML + 12, y + 5);

      y += rh;
    });
    y += 6;
  }

  // ════════════════════════════════════════════════════════════════════════════
  // RISK REGISTER
  // ════════════════════════════════════════════════════════════════════════════
  if (report.risks.length > 0) {
    // Check space for section title + table header + first row
    need(14 + 9 + 20);
    sectionTitle("Risk Register");
    drawTable(
      ["Risk", "Severity", "Description"],
      [0.30, 0.15, 0.55],
      report.risks.map((r) => ({
        cells: [r.title, r.severity, r.description],
        badge: { colIndex: 1, label: r.severity, severity: r.severity },
      }))
    );
  }

  // ════════════════════════════════════════════════════════════════════════════
  // RECOMMENDATIONS
  // ════════════════════════════════════════════════════════════════════════════
  if (report.recommendations.length > 0) {
    // Check space for section title + table header + first row
    need(14 + 9 + 20);
    sectionTitle("Recommendations");
    drawTable(
      ["Recommendation", "Priority", "Action"],
      [0.32, 0.15, 0.53],
      report.recommendations.map((r) => ({
        cells: [r.title, r.priority, r.action],
        badge: { colIndex: 1, label: r.priority, severity: r.priority },
      }))
    );
  }

  // ════════════════════════════════════════════════════════════════════════════
  // TEAM PERFORMANCE
  // ════════════════════════════════════════════════════════════════════════════
  if (report.teamPerformance) {
    sectionTitle("Team Performance");
    textBox(report.teamPerformance);
  }

  // ════════════════════════════════════════════════════════════════════════════
  // FOOTER on all pages
  // ════════════════════════════════════════════════════════════════════════════
  const total = doc.getNumberOfPages();
  for (let p = 1; p <= total; p++) {
    doc.setPage(p);
    drawFooter();
  }

  // Save
  const slug = (typeof report.projectId === "object" ? report.projectId.title : "report")
    .replace(/\s+/g, "-")
    .toLowerCase();
  doc.save(`report-${slug}-${new Date().toISOString().split("T")[0]}.pdf`);
}
